# Generated by Django 2.1 on 2019-04-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price_old', models.IntegerField(blank=True)),
                ('price', models.IntegerField()),
                ('photo', models.IntegerField()),
                ('print_small_size', models.CharField(max_length=30)),
                ('print_small', models.IntegerField()),
                ('print_large_size', models.CharField(blank=True, max_length=30)),
                ('print_large', models.IntegerField(blank=True)),
                ('print_a', models.IntegerField(blank=True)),
                ('shooting_time', models.IntegerField(verbose_name='Shooting (Hour)')),
                ('shooting_location', models.IntegerField(verbose_name='Number of Location')),
                ('remark', models.CharField(max_length=100)),
            ],
        ),
    ]
