# Generated by Django 2.2.4 on 2019-08-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='print_a',
        ),
        migrations.AddField(
            model_name='session',
            name='print_album',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='print_large',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='print_large_size',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
