# Generated by Django 2.1.7 on 2019-05-02 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='angle',
            new_name='fov',
        ),
    ]
