# Generated by Django 2.2.4 on 2019-08-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0002_auto_20190810_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('P', 'Portrait'), ('G', 'Graduation'), ('W', 'Prewedding'), ('F', 'Family'), ('B', 'Baby'), ('C', 'Ceremony'), ('D', 'Product')], default='Portrait', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='static/img/portfolio')),
                ('lighting', models.CharField(choices=[('u', 'Under'), ('n', 'normal'), ('o', 'over')], max_length=1)),
                ('situation', models.CharField(choices=[('u', 'Under'), ('n', 'normal'), ('o', 'over')], max_length=1)),
                ('mood', models.CharField(choices=[('u', 'Under'), ('n', 'normal'), ('o', 'over')], max_length=1)),
                ('fov', models.CharField(choices=[('s', 'Wide'), ('n', 'normal'), ('t', 'tele')], max_length=1)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Album')),
            ],
        ),
    ]
